name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza a cada 24h

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobra
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push dos arquivos
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualizando a animação Snake"
          branch: output
